import { ElevenLabsClient } from "@elevenlabs/elevenlabs-js";
import * as admin from "firebase-admin";
import { FieldValue } from "firebase-admin/firestore";
import { Readable } from "stream";
import { ReadableStream } from "stream/web";
import * as functions from "firebase-functions/v1";
import config from "./config";
import { GenerateAudioRequest } from "./types";
import { buildRequest, BuildRequestOptions, getFileExtension } from "./util";

const logger = functions.logger;

admin.initializeApp();

const elevenlabs = new ElevenLabsClient({
  apiKey: config.elevenLabsApiKey, // Defaults to process.env.ELEVENLABS_API_KEY
});

logger.log("Initializing text-to-speech extension with config:", {
  ...config,
  elevenLabsApiKey: config.elevenLabsApiKey ? "[REDACTED]" : "",
});

export const elevenLabsTextToSpeech = functions.firestore
  .document(`${config.collectionPath}/{docId}`)
  .onWrite(async (change) => {
    const before = change?.before?.data();
    const after = change?.after?.data();

    const snap = change.after;
    if (
      snap?.exists &&
      snap?.data().text &&
      (!before || ["text", "outputFormat", "modelId", "voice"].some((p) => before[p] !== after[p])) &&
      // When updates are not enabled, only generate audio if there is no audioPath yet
      (config.enableUpdates || !after.audioPath)
    ) {
      const { text, outputFormat, modelId, voice } = snap.data() as BuildRequestOptions;

      const request = config.enablePerDocumentOverrides
        ? buildRequest({
            text,
            outputFormat,
            modelId,
            voice,
          })
        : buildRequest({ text });

      const audioStream = await processText(request);
      if (audioStream) {
        const fileExtension = getFileExtension(request.outputFormat);

        const fileName = config.storagePath
          ? `${config.storagePath}/${snap.id}${fileExtension}`
          : `${snap.id}${fileExtension}`;

        const bucket = admin.storage().bucket(config.bucketName);

        const file = bucket.file(fileName);

        logger.log("Uploading audio to storage with filename:", fileName, {
          includeCustomMetadata: config.includeCustomMetadata,
          cacheControl: config.cacheControl,
        });

        await new Promise<void>((resolve, reject) => {
          audioStream
            .pipe(
              file.createWriteStream({
                metadata: {
                  // note that we nest "metadata" for our custom metadata
                  ...(config.includeCustomMetadata
                    ? {
                        metadata: {
                          description: "Audio generated by ElevenLabs text-to-speech extension",
                          documentId: snap.id,
                          documentPath: snap.ref.path,
                          text: request.text,
                          voice: request.voice,
                          modelId: request.modelId,
                          outputFormat: request.outputFormat,
                        },
                      }
                    : {}),
                  ...(config.cacheControl
                    ? {
                        cacheControl: config.cacheControl,
                      }
                    : {}),
                },
              }),
            )
            .on("error", reject)
            .on("finish", resolve);
        });

        logger.log(`Audio uploaded to gs://${config.bucketName}/${fileName}`, { metadata: file.metadata });

        await snap.ref.update({
          status: "done",
          audioPath: `gs://${config.bucketName}/${fileName}`,
          audioCreatedAt: FieldValue.serverTimestamp(),
        });
      } else {
        logger.error("No audio stream returned from ElevenLabs");
        await snap.ref.update({
          status: "failed",
          generatingAudioFailed: true,
        });
      }
    }
  });

async function processText(request: GenerateAudioRequest) {
  // Performs the text-to-speech request
  try {
    logger.log("Generating audio with request:", request, { maxRetries: config.maxRetries });
    const voiceId = await getVoiceId(request.voice || "Rachel");
    const textToSpeechRequest = { ...request };
    delete textToSpeechRequest.voice;
    const audioStream = await elevenlabs.textToSpeech.convert(voiceId, textToSpeechRequest, {
      maxRetries: config.maxRetries,
    });
    return Readable.fromWeb(audioStream as unknown as ReadableStream<Uint8Array>);
  } catch (e) {
    logger.error("Failed to generate audio with ElevenLabs", getSafeErrorDetails(e));
    return null;
  }
}

async function getVoiceId(voice: string) {
  if (/^[A-Za-z0-9]{20}$/.test(voice)) {
    return voice;
  }

  const response = await elevenlabs.voices.search({ search: voice, pageSize: 100 });
  const matchingVoice =
    response.voices.find((v) => v.name?.toLowerCase() === voice.toLowerCase()) || response.voices[0];

  if (!matchingVoice) {
    throw new Error(`No ElevenLabs voice found matching "${voice}"`);
  }

  return matchingVoice.voiceId;
}

function getSafeErrorDetails(error: unknown) {
  if (error instanceof Error) {
    return {
      message: error.message,
      name: error.name,
      statusCode: getErrorStatusCode(error),
    };
  }

  return {
    message: typeof error === "string" ? error : "Unknown ElevenLabs error",
    statusCode: getErrorStatusCode(error),
  };
}

function getErrorStatusCode(error: unknown) {
  if (typeof error === "object" && error !== null && "statusCode" in error) {
    return (error as { statusCode?: unknown }).statusCode;
  }

  return undefined;
}
